stage('Build') {
    steps {
        dir('my_repos/maven_first_example/my-app') {
            sh 'mvn -B clean compile'
        }
    }
}

stage('Test') {
    steps {
        dir('my_repos/maven_first_example/my-app') {
            sh 'mvn -B test'
        }
    }
}

stage('Package') {
    steps {
        dir('my_repos/maven_first_example/my-app') {
            sh 'mvn -B -DskipTests package'
        }
    }
}          
